Account/urls.py
from django.urls import path, reverse_lazy
from . import views

from django.contrib.auth import views as auth_views

app_name = "account"

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('register/', views.register_user, name='user_register'),
    path('logout/', views.user_logout, name='user_logout'),
    path('password-change', views.password_change, name='password_change'),
    path('reset_password/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('account:password_reset_done')), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="reset_password_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="reset_password_complete"),

    path('profile/', views.profile, name="profile"),

]

blog/urls.py
from django.urls import path
from . import views

from .feeds import LastetsPostsFeeds


app_name = 'blog'

urlpatterns = [
    path('', views.list_view, name='home'),
    path('posts/', views.list_view, name='list_view'),
    path('account/', views.UserAccount, name='user_account'),
    path('contact-us/', views.contactus, name='contact-us'),
    path('posts/<int:pk>/<slug:slug>/', views.post_detail, name='post_detail'),
    path('posts/<int:pk>/<slug:slug>/edit', views.post_edit, name='post_edit'),
    path('feed/', LastetsPostsFeeds(), name="post_feed"),
    path('search/', views.post_search, name='post_search'),
    path('categories/<str:cat>', views.list_with_category, name="list_with_category")
]

galleryViewer/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
 'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('account/', include('Account.urls', namespace='account')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from .models import Comment, Account
from django import forms

import re


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class AccountForm(forms.Form):
    GENDER_CHOICES = (
        ('man', 'Man'),
        ('woman', 'Woman')
    )
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=50, required=True)
    phone = forms.CharField(max_length=12, required=False)
    gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect, required=True)
    address = forms.CharField(max_length=500, widget=forms.Textarea, required=False)
    age = forms.IntegerField(required=False)
    email = forms.EmailField(required=False)

    def clean_first_name(self):
        name = self.cleaned_data['first_name']
        if len(name) < 3:
            raise forms.ValidationError("your name at least should be 3 Chars")
        elif len(name) > 30:
            raise forms.ValidationError("your name shouldnt be morethan 30 Chars")
        else:
            return name

    def clean_last_name(self):
        last = self.cleaned_data['last_name']
        if len(last) < 3:
            raise forms.ValidationError("your name at least should be 3 Chars")
        elif len(last) > 50:
            raise forms.ValidationError("your name shouldnt be morethan 50 Chars")
        else:
            return last

    def clean_phone(self):
        phone = self.cleaned_data['phone']

        if phone.isalpha():
            raise forms.ValidationError("enter correct phone")

        elif len(phone) < 10 or len(phone) > 11:
            raise forms.ValidationError("enter correct phone")

        else:
            return phone

    def clean_email(self):
        email = self.cleaned_data['email']

        regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'

        if (re.fullmatch(regex, email)):
            return email
        else:
            raise forms.ValidationError("Invalid Email, Enter correct one")


class ContactusForm(forms.Form):
    name = forms.CharField(max_length=30, required=True)
    subject = forms.CharField(max_length=25, required=True)
    email = forms.EmailField(max_length=50, required=True)
    phone = forms.CharField(max_length=11, required=False)
    message = forms.CharField(widget=forms.Textarea, required=True)

    def clean_name(self):
        name = self.cleaned_data['name']
        if len(name) < 3:
            raise forms.ValidationError("your name at least should be 3 Chars")
        elif len(name) > 50:
            raise forms.ValidationError("your name shouldnt be more than 50 Chars")
        else:
            return name

    def clean_subject(self):
        sub = self.cleaned_data['subject']
        if len(sub) < 3:
            raise forms.ValidationError("your subject at least should be 3 Chars")
        elif len(sub) > 50:
            raise forms.ValidationError("your subject shouldnt be more than 25 Chars")
        else:
            return sub

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if phone.isalpha():
                raise forms.ValidationError("enter correct phone number")

            elif len(phone) < 10 or len(phone) > 11:
                raise forms.ValidationError("enter correct phone number")
            else:
                return phone

    def clean_email(self):
        email = self.cleaned_data['email']

        regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'

        if (re.fullmatch(regex, email)):
            return email
        else:
            raise forms.ValidationError("Invalid Email, Enter correct one")

    def clean_message(self):
        msg = self.cleaned_data['message']
        if len(msg) < 10:
            raise forms.ValidationError("your message at least should be 10 Chars")
        elif len(msg) > 250:
            raise forms.ValidationError("your name shouldnt be more than 259 Chars")
        else:
            return msg


class SharePostForm(forms.Form):
    email = forms.EmailField(max_length=50, required=True)

    def clean_email(self):
        email = self.cleaned_data['email']

        regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'

        if (re.fullmatch(regex, email)):
            return email
        else:
            raise forms.ValidationError("Invalid Email, Enter correct one")

class SearchForm(forms.Form):
    query = forms.CharField(max_length=50, required=True)


blog/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.models import User
from .models import Post, Account, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentForm, AccountForm, ContactusForm, SharePostForm, SearchForm
from Account.forms import AddPhotoForm
from django.core.mail import send_mail

from django.contrib import messages

from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank

from .models import Tag

from django.contrib.auth.decorators import login_required



def list_view(request):
    # Get All Published Posts
    posts = Post.published.all()

    # Get All Available Categories
    categories = Tag.objects.filter(status=True)

    # Paginate Site With 6 Items Per A Page
    paginator = Paginator(posts, 6)
    page = request.GET.get('page')

    # Post Of Certain Page
    try:
        posts = paginator.page(page)

    # If Page Not Integer
    except PageNotAnInteger:
        posts = paginator.page(1)

    # If Page NOt Exists
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'partials/content.html', {'posts': posts, 'page': page, 'categories': categories})


def post_detail(request, pk, slug):
    user = request.user
    post = Post.objects.get(slug=slug, id=pk)
    comments = post.comments.filter(active=True)

    # To Understand Email Sent
    sent = False

    # For New Comment
    new_comment = None

    # Handle The Forms
    if request.method == 'POST':
        # Define Forms
        share_form = SharePostForm()
        comment_form = CommentForm()
        # Handle Share Post Form
        if "shareForm" in request.POST:
            # Create Object Of ShareForm
            share_form = SharePostForm(request.POST)
            if share_form.is_valid():
                email = share_form.cleaned_data['email']
                subject = post.title
                link = request.build_absolute_uri(post.get_absolute_url())
                message = f"post \"{subject}\" sent to you \n link: {link}"
                # Send An Email To User
                send_mail(subject, message, 'EMAIL ADDRESS', {email}, fail_silently=False)
                sent = True

                messages.warning(request, message="Email Has Been Sent")
                return redirect(reverse('blog:post_detail', args=[pk, slug]))
            else:
                share_form = SharePostForm()

        # Handle Comment Form
        if "commentForm" in request.POST:
            # A comment was posted
            comment_form = CommentForm(data=request.POST)
            if comment_form.is_valid():
                # Create Comment object but don't save to database yet
                new_comment = comment_form.save(commit=False)
                # Assign the current post to the comment
                new_comment.post = post
                # Save the comment to the database
                new_comment.save()

                messages.success(request, message=f"Successfully Commented")

                return redirect(reverse('blog:post_detail', args=[pk, slug]))
            else:
                comment_form = CommentForm()
    else:
        share_form = SharePostForm()
        comment_form = CommentForm()

    context = {
        'post': post,
        'share_form': share_form,
        'sent': sent,
        'comment_form': comment_form,
        'comments': comments,
        'user': user,
    }
    return render(request, 'post/post_detail.html', context)


@login_required
def post_edit(request, pk, slug):
    post = Post.published.get(id=pk, slug=slug)
    categories = Tag.objects.filter(status=True)

    # Get Current Post Category
    curent_cat = str(post.tag.first())

    if request.method == "POST":
        # To Delete Post
        if "delete" in request.POST:
            post.delete()
            return redirect('account:profile')

        photoForm = AddPhotoForm(data=request.POST)
        if photoForm.is_valid():

            # Get User Form Data
            cd = photoForm.cleaned_data
            title = cd["title"]
            description = cd["description"]
            slug = title.replace(" ", "-")
            tag = Tag.objects.get(id=cd['tag'])

            # Save New Data On Post
            post.title = title
            post.description = description
            post.slug = slug
            post.tag.add(tag)

            # Save And Update Post
            post.save()

            return redirect('account:profile')
    else:
        photoForm = AddPhotoForm()
    return render(request, 'post/post_edit.html', {'post': post, 'categories':categories, 'curent_cat': curent_cat})


@login_required
def UserAccount(request):
    user = request.user

    # Get User Account If Exists
    try:
        account = Account.objects.get(user=user)

    # Create User Account If Not Exists
    except:
        account = Account.objects.create(user=user)

    if request.method == "POST":
        form = AccountForm(data=request.POST)
        if form.is_valid():

            # Get And Save New Data
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.email = form.cleaned_data["email"]
            account.gender = form.cleaned_data['gender']
            account.address = form.cleaned_data['address']
            account.age = form.cleaned_data['age']
            account.phone = form.cleaned_data['phone']

            # Save And Update User And Account
            user.save()
            account.save()

            return redirect('blog:list_view')

        else:
            return render(request, 'blog/forms/account_form.html', {'form': form, 'account': account})
    form = AccountForm()
    return render(request, 'blog/forms/account_form.html', {'form': form, 'account': account})


def contactus(request):
    # To Understand Email Sent
    sent = False
    if request.method == "POST":
        form = ContactusForm(request.POST)
        if form.is_valid():

            # Get User Form Data
            cd = form.cleaned_data
            name = cd['name']
            subject = cd['subject']
            email = cd['email']
            phone = cd['phone']
            message = cd['message']
            text = f"from: {name}\nemail: {email}\nphone: {phone}\nmessage: {message}"

            # Send Email To Admin
            send_mail(subject, text, 'EMAIL ADDRESS', ['amirsmvb@gmail.com'], fail_silently=False)

            # Email Sent
            sent = True

            # Send Success Message To Template
            messages.success(request, "Thanks! Your Meesage Sent.")

            return redirect('blog:contact-us')
    else:
        form = AccountForm()
    return render(request, 'blog/forms/contactus_form.html', {'form': form, 'sent': sent})


def post_search(request):
    form = SearchForm()
    # Phrase That User Search
    query = None

    # Founded Results
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]

            # Search In Posts
            search_vector = SearchVector('title', weight='A') + SearchVector('description', weight='B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(search=search_query).order_by('-rank')

    context = {
        'query': query,
        'posts': results,
        'form': form
    }
    return render(request, 'partials/content.html', context)


def list_with_category(request, cat):
    # Get Published Posts With Specific Categories
    posts = Post.published.filter(tag__name=cat)

    # To Show All Posts
    if cat == "all":
        posts = Post.published.all()

    # Paginating Pages
    paginator = Paginator(posts, 6)
    categories = Tag.objects.filter(status=True)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'partials/content.html', {'posts': posts, 'page': page, 'categories': categories, 'current_cat': cat})




blog/templates/partials/content.html
{% extends "blog/parent/base.html" %}
{% load blog_tags %}
{% load static %}
{% block title %}Home{% endblock %}

{% block header %}
    <style>
        .image-thumbail {

            height: 200px;
            object-fit: cover;
        }

        .list-group-item a {
            text-decoration: none;
            color: black;
        }
    </style>
{% endblock %}

{% block content %}

    {% if query %}
        {% if total_posts == 0 %}
            <h1>No Photo</h1>
        {% endif %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with posts.count as total_posts %}
                Found {{ total_posts }} result{{ total_posts|pluralize }}
            {% endwith %}
        </h3>
    {% endif %}


    <div class="row">
        <div class="col-md-3">


            <ul class="list-group d-inline-flex p-3 mr-auto" style="width: 250px">

                <li class="list-group-item d-flex justify-content-between align-items-center"
                    style="background-color: rgba(219,219,219,0.36)">
                    Categories
                </li>
                <a href="{% url 'blog:list_with_category' 'all' %}" class="text-dark" style="text-decoration: none">

                    <li class="list-group-item d-flex justify-content-between align-items-center {% if current_cat == 'all' %}bg-info{% endif %}">
                        All
                    </li>
                </a>
                {% for cat in categories %}
                    <a href="{% url 'blog:list_with_category' cat %}" class="text-dark" style="text-decoration: none">

                        <li class="list-group-item d-flex justify-content-between align-items-center {% if cat.name == current_cat %}bg-info{% endif %}">
                            {{ cat }}
                            <span class="badge badge-primary badge-pill">{{ cat.tag.count }}</span>
                        </li>
                    </a>
                {% endfor %}

            </ul>
        </div>

        <div class="col-md-9">
            <div class="row">

                {% for post in posts %}
                    <div class="col-md-4">
                        <div class="card my-2">
                            <img class="image-thumbail" src="{{ post.image.url }}" alt="Card image cap">

                            <div class="card-body">
                                <h4 class="text-dark">
                                    {{ post.title }}
                                </h4>
                                <small>
                                    Category:
                                    {% for tag in post.tag.all %}
                                        <a href="{% url "blog:list_with_category" tag %}">{{ tag }}</a>,
                                    {% endfor %}
                                </small>
                            </div>
                            <a href="{{ post.get_absolute_url }}" class="btn btn-outline-dark btn-sm m-1">View</a>
                        </div>
                    </div>
                {% empty %}
                    <h3>No photos...</h3>
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}

blog/templates/partials/navbar.html
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <button
                class="navbar-toggler"
                type="button"
                data-mdb-toggle="collapse"
                data-mdb-target="#navbarExample01"
                aria-controls="navbarExample01"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
            <i class="fas fa-bars"></i>
        </button>

        <div class="collapse navbar-collapse" id="navbarExample01">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" aria-current="page" href="{% url "blog:list_view" %}">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url "blog:contact-us" %}">Contact Us</a>
                </li>
                <li class="nav-item">
                    {% if request.user.is_authenticated %}
                        <a class="nav-link" href="{% url 'account:profile' %}">Profile</a>
                        {% else %}
                        <a class="nav-link" href="{% url 'account:user_login' %}">login/register</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>

    <!-- Search Form -->
    <form method="get" action="{% url 'blog:post_search' %}" style="background-color: #343A40">
        <div class="form-outline" style="margin-right: 30px">
            <input type="search" id="form1" class="form-control" placeholder="Search"
                   aria-label="Search" name="query" value="{{ request.GET.query }}"/>
        </div>
    </form>
    <!-- End Of Search Form-->


    <!-- rss -->
    <a href="{% url 'blog:post_feed' %}" style="float: right;">
        <img src="{% static 'images/rss_icon.png' %}" width="25px">
    </a>
    <!-- end of rss -->

</nav>
<!-- Navbar -->

blog/templates/partials/pagination.html
<nav class="Page navigation example pagination-container">
    <div class="pagination">

        {% if page.has_previous %}
            <a class="pagination-newer" href="?page={{ page.previous_page_number }}">PREV</a>
        {% endif %}

        <span class="pagination-inner">

		    {% for p in page.paginator.page_range %}
                {% if p == page.number %}
                    <a class="pagination-active" href="?page={{ p }}">{{ p }}</a>
                {% else %}
                    <a href="?page={{ p }}">{{ p }}</a>
                {% endif %}
            {% endfor %}

        </span>

        {% if page.has_next %}
            <a class="pagination-older" href="?page={{ page.next_page_number }}">NEXT</a>
        {% endif %}

    </div>
</nav>


